### ISSUE TITLE
The counterfactual baseline calculation seems inconsistent with the paper

### ISSUE THREAD

**Issue by pigeonmg** [Qiushi-Lin/SACHA#1]
The function `get_coma_baseline` in model.py seems inconsistent with the description in the paper, it shows
```
temp_action = copy.deepcopy(action)
temp_action[i] = j
p += self.forward(obs, action, state)[i] / self.action_dim
```
But I believe that the `get_coma_baseline` function should include an additional parameter 'pi', representing the current actor's policy distribution, and the code may be as follows,
```
temp_action = copy.deepcopy(action)
temp_action[i] = (torch.tensor(j)).to(temp_action[i].device)
p += self.forward(obs, temp_action, state)[i][j]*pi[i][j]
```

**Comment by Qiushi-Lin** [comment]
Yes, you are right. I will correct it and find spare time to test it out. Thank you for pointing it out.
