### ISSUE TITLE
TypeError: AttentionPolicy.forward() missing 1 required positional argument: 'state_n'

### ISSUE THREAD

**Issue by pigeonmg** [Qiushi-Lin/SACHA#2]
I‘m sorry to disturb you in your busy schedule. But when I run **train.py**, there is the following error.
~~~
TypeError: AttentionPolicy.forward() missing 1 required positional argument: 'state_n'
~~~
 I think there might be a missing argument on **line 51 of train.py**. How to solve this problem? 
Thanks for your kindness.

**Comment by Qiushi-Lin** [comment]
Sorry, some version control issues. I will post a fix soon.
